# Bayesian <span style="font-variant:small-caps;">NeuralPbc</span>

## Bayesian <span style="font-variant:small-caps;">NeuralPbc</span>

<br/>

:::{.r-stack}

:::{.fragment .fade-in-then-out fragment-index=0}
::: {.callout-tip icon="false"}
## <span style="font-variant:small-caps;">NeuralPbc</span> Optimization Problem 

$$
\begin{aligned}
\underset{\theta}{\text{minimize}} && J(\phi, u^\theta) &= \mathbb{E}_{x_0 \in \mathcal{D}_N}[ \ell( \phi(x_0, u, T), u) ], \\
\text{subject to} &&
\begin{bmatrix}
  \dot{q} \\ \dot{p}
\end{bmatrix} &=
\begin{bmatrix}
  0 & I \\ -I & 0
\end{bmatrix}
\begin{bmatrix} \nabla_q H \\ \nabla_p H \end{bmatrix} + 
\begin{bmatrix}
  0 \\ \Omega
\end{bmatrix} u^{\theta},
\\
&& u^\theta &= \Omega^{\dagger}(\nabla_q H  - \nabla_q H_d^\theta).
\end{aligned}
$$
:::
:::

:::{.fragment .fade-in-then-out fragment-index=1}
::: {.callout-note icon="false"}
## Bayesian <span style="font-variant:small-caps;">NeuralPbc</span> Optimization Problem 
$$
\begin{aligned}
    \underset{z}{\text{minimize}} && J(\phi, u^\theta) &= \mathbb{E}_{x_0 \in \mathcal{D}_N}[ \ell( \phi(x_0, u, T), u) ], \\
    \text{subject to} &&
    \begin{bmatrix}
    \dot{q} \\ \dot{p}
    \end{bmatrix} &=
    \begin{bmatrix}
    0 & I \\ -I & 0
    \end{bmatrix}
    \begin{bmatrix} \nabla_q H \\ \nabla_p H \end{bmatrix} + 
    \begin{bmatrix}
    0 \\ \Omega
    \end{bmatrix} u^{\theta},
    \\
    && u^\theta &= \Omega^{\dagger}(\nabla_q H  - \nabla_q H_d^\theta),\\
    && \theta &\sim Q(\theta; z).
\end{aligned} 
$$
:::
:::


:::

:::{.fragment .fade-in fragment-index=1}
* The parameter $z$ of the posterior $Q(\theta;z)$ is inferred from running cost $J(\phi, u^\theta)$
* $H_d^\theta$ is a Bayesian neural network (BNN)
:::

## Uncertainty Modeling

* We provide more structure to the variance of the Bayesian controllers

::: {.callout-note icon="false"}
## Bayesian <span style="font-variant:small-caps;">NeuralPbc</span> Optimization Problem 
$$
\begin{aligned}
    \underset{z}{\text{minimize}} && J(\phi, u^\theta) &= \mathbb{E}_{x_0 \in \mathcal{D}_N}[ \ell( \phi(x_0, u, T), u) ], \\
    \text{subject to} &&
    \dd x &= \left(
        \begin{bmatrix}\phantom{-}\nabla_p H \\-\nabla_q H \end{bmatrix} + \begin{bmatrix} 0 \\ \Omega \end{bmatrix} u^{\theta}(x) \right) \dd t + \nabla_x u(x) \dd W_t, \\
    && u^\theta &= \Omega^{\dagger}(\nabla_q H  - \nabla_q H_d^\theta),\\
    && \theta &\sim Q(\theta; z), \\
    && p_s &\sim \mathcal{N}(\hat{p}_s, \sigma_p).
\end{aligned} 
$$
:::
* **Objective**: maximize <span style="font-variant:small-caps;">Elbo</span> 

\begin{gather*}
  \mathcal{L}(J,z) = \mathbb{E}_{\theta \sim Q} \left[\ln(P(J \mid \theta)P(\theta)) - \ln(Q(\theta;z)) \right] \\ 
  P(J | \theta) = \mathcal{N}(J \; | \; 0, s).
\end{gather*}


## <span style="font-variant:small-caps;">NeuralPbc</span>: Hybrid System

<br/>

::: {layout="[50,-5,50]" layout-valign="center" .fragment fragment-index=0}

:::{.callout-note icon="false"}
## Passive Smooth System
$$
H\left(  x(t_1) \right) \leq  H\left(  x(t_0) \right) + \int_{t_0}^{t_1} s(u(t), y(t)) \, \text{d}t
$$
:::

:::{.callout-important icon="false"}
## Passive Hybrid System
\begin{gather*}
H\left(  x(t_1) \right) \leq  H\left(  x(t_0) \right) + \int_{t_0}^{t_1} s(u(t), y(t)) \, \text{d}t \\
H(x^+) \leq H(x^-)
\end{gather*}
:::

:::

:::{.fragment fragment-index=1}
:::{.callout-warning icon="false" }
## <span style="font-variant:small-caps;">NeuralPbc</span> for contact-rich system
\begin{aligned}
    \underset{\theta}{\textrm{minimize}} 
    & & J(\phi, u^\theta) &= \mathbb{E}_{x_0 \in \mathcal{D}_N}[ \ell( \phi(x_0, u, T), u) ], \\%
    \textrm{subject to}
    & & M(q) &\dd \dot{q} + h(q, \dot{q}, \theta)\dd t - \dd R  = 0,\\%
    & & u^{\theta} &= \Omega^{\dagger}(\nabla_q H  - \nabla_q H_d).%
\end{aligned}
:::
:::

## Bayesian <span style="font-variant:small-caps;">NeuralPbc</span>: Hybrid System

:::{.callout-warning icon="false" }
## <span style="font-variant:small-caps;">NeuralPbc</span> for contact-rich system

\begin{aligned}
    \underset{z}{\textrm{minimize}} 
    & & & J(\phi, u) = \mathbb{E}_{x_0 \in \mathcal{D}_N}[\ell(\phi(x_0, u^\theta, T), u^\theta)], \\
    \textrm{subject to}
    & & M(q) &\dd \dot{q} + h(q, \dot{q}, \theta)\dd t - \dd R  = 0,\\
    & & u^{\theta} &= \Omega^{\dagger}(\nabla_q H  - \nabla_q H_d^\theta), \\
    & & p_s &\sim \mathbb{U}(p_{min}, p_{max}), \\
    & & \theta &\sim Q(\theta; z).
\end{aligned}

:::
{{< video contents/assets/rw_uneven.mp4 >}}
