---
pagetitle: "Robust Control of Contact-Rich Robots via Neural Bayesian Inference"
author-meta: "Nardos Ashenafi"
institute: "Boise State University"
---

## Robust Control of Contact-Rich Robots via Neural Bayesian Inference {.center .smaller}
<!-- ###################################################################### -->

<hr/>

*Doctoral Dissertation Defense*

<br/>

::: {layout="[100,60]"}
__Candidate__: <br/>
Nardos Ashenafi:mortar_board: <br/>
Electrical and Computer Engineering Department <br/>
Boise State University, Boise, Idaho, USA 

__Supervisory Committee__: <br/>
Aykut Satici, Ph.D. <br/>
John Chiasson, Ph.D. <br/>
Kurtis Cantley, Ph.D. <br/>
Hao Chen, Ph.D. <br/>
Arash Komaee, Ph.D. 
:::


## Publications and Contributions 

<br>

<!-- :::: {.columns}
::: {.column width="65%"} -->

::: {.fragment .fade-in-then-semi-out fragment-index=0}
### <span style="font-variant:small-caps;">Published</span>
* ***CCTA 2021***: Cooperative Manipulation
* ***ACC 2022***: Bayesian <span style="font-variant:small-caps;">NeuralPbc</span>
* ***L-CSS 2022***: Bayesian <span style="font-variant:small-caps;">NeuralPbc</span>
    + ***CDC 2022***
* ***Arxiv 2022***: Control Design via Bayesian Inference: Theoretical Justification of Robustness
<!-- ::: -->

:::

<!-- ::: {.column width="35%"}  -->
::: {.fragment .fade-in fragment-index=1}
### <span style="font-variant:small-caps;">Upcoming Submissions</span>
* ***TACON 2023***: Control of Hybrid Dynamical Systems via Deep-net Mixture of Experts
* ***IJRR 2023***: Data Driven Passivity-Based Control of the Rimless Wheel on Uneven Terrain
:::
<!-- ::: -->
<!-- ::::  -->